// get all users, expected response: []
###
GET http://localhost:8080/users
Authorization: 

###
POST http://localhost:8080/authenticate
Content-Type: application/json

{
    "userID": "admin",
    "password": "123"
}

###
POST http://localhost:8080/authenticate
Content-Type: application/json

{
    "userID": "firstUser",
    "password": "456"
}