POST http://localhost:8080/authenticate/login
Content-Type: application/json

{
    "userID": "admin",
    "password": "123"
}

###
GET http://localhost:8080/users/admin

###
GET http://localhost:8080/users/

###
POST http://localhost:8080/users/3/false

###
POST http://localhost:8080/users/
content-Type: application/json

{
    "userID": "5",
    "userName": "ThridTestUser"
}

###
DELETE http://localhost:8080/users/4